---
title: "PovcalNet What is New"
description: |
  This page is a replica of the old "What is New" of the now deprecated PovcalNet system. The intention of this page it to keep institutional memory publicly available.
categories:
  - Data update
  - PovcalNet
author:
  - name: PIP Technical Team
date: 2021-06-21
output:
  distill::distill_article:
    toc: true
    number_sections: true
    toc_depth: 4
    # code_folding: true
    toc_float: true
    collapsed: false
    smooth_scroll: true
    self_contained: false
editor_options: 
  markdown: 
    wrap: sentence
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# 2021/06/21

In June 2021, minor revisions were made to four sets of survey estimates:

-   In March 2021 the welfare aggregates for Honduras from 2014-2018 were revised reflecting updates to the poverty measurement methodology (See March 2021 What's New for details).
    This methodology is now also applied to 2011-2013 to extend the comparability of the series.
    Minor changes have also been made to the 2014-2015 estimates based on revised raw data correcting previously missing values from conditional cash transfer income.
    The changes to the poverty rate (using the \$1.90 poverty line) are all within 2 percentage points.

-   For Nicaragua, the consumption vectors in 1993, 1998, 2001, and 2005 were updated resulting in poverty rates (using the \$1.90 poverty line) changing by less than 1 percentage point.

-   In March 2021 we meant to update the income aggregate for Mexico for the years 1989-1998 according to the SEDLAC-03 harmonization.
    Erroneously, this did not happen for the 1989 survey, which has been updated now.
    Details behind the changes can be found in the March 2021 What's [New document](https://documents.worldbank.org/en/publication/documents-reports/documentdetail/654971615585402030/march-2021-povcalnet-update-what-s-new).

-   We have corrected a minor error in the conversion of the Indonesian 2019 distribution from LCU to 2011 PPPs, which shifts the mean upwards by about 1%.

# 2021/03/16

The March 2021 global poverty update from the World Bank presents new poverty estimates for 2019, and revises the previously published global and regional estimates from 1981 to 2018.
The update includes new surveys that have been received and processed, including new surveys using imputed consumption data, as well as several changes to the existing data.
Some changes reflect improvements in the welfare aggregate based on new harmonization efforts and more available information.
[This document](https://documents.worldbank.org/en/publication/documents-reports/documentdetail/654971615585402030/march-2021-povcalnet-update-what-s-new) outlines the changes made to the underlying data by country, and explains the reasons why the changes have been made.

# 2020/09/10

The September 2020 global poverty update from the World Bank mainly involves the adoption of the revised 2011 PPPs for the estimation of global poverty.
In addition, the coverage rule for reporting regional and global poverty aggregates has been reviewed.
Historical regional and global aggregates are now reported with an annual frequency throughout instead of the intervals with varying lengths.
Only two surveys have been added: Nigeria (2017/2018) and Canada (2017).
Some welfare aggregates from the Luxembourg Income Study (LIS) have been revised.
National accounts and population input data have been updated.
[This document](https://documents.worldbank.org/en/publication/documents-reports/documentdetail/144451599591697923/september-2020-povcalnet-update-what-s-new) explains these changes in detail and the reasoning behind them.
The data are used for the analysis of global poverty in the Poverty and Shared Prosperity Report 2020.

# 2020/03/17

The March 2020 global poverty update from the World Bank presents new poverty estimates for 2018, and revises the previously published global and regional estimates from 1981 to 2015.
The update includes new surveys that have been received and processed, as well as several changes to the existing data.
Some changes reflect improvements in the welfare aggregate based on new harmonization efforts and more available information.
[This document](https://documents.worldbank.org/en/publication/documents-reports/documentdetail/407961584980637951/march-2020-povcalnet-update-whats-new) outlines the changes made to the underlying data by country, and explains the reasons why the changes have been made.

# 2019/09/24

The September 2019 global poverty update from the World Bank includes revised survey data which lead to minor changes in the most recent global poverty estimates.
The update includes revisions to 18 surveys from four countries.
[This document](https://documents.worldbank.org/en/publication/documents-reports/documentdetail/344401569259571927/september-2019-povcalnet-update-whats-new) outlines the changes made to the underlying data.
In this release, we provide metadata on comparability of poverty estimates within countries over time.
[This document](https://documents.worldbank.org/en/publication/documents-reports/documentdetail/344401569259571927/september-2019-povcalnet-update-whats-new) (section 4) provides a more detailed description of the comparability metadata database.
The database can be downloaded [here](https://datacatalog.worldbank.org/int/home).

# 2019/03/21

The March 2019 global poverty update from the World Bank revises the previously published global and regional estimates from 1981 to 2015, using new data and surveys.
The update includes 51 new surveys that have been received and processed, as well as several changes to the existing surveys and revised CPI, population and national accounts data.
Some changes reflect improvements in the welfare aggregate based on new harmonization efforts and more available information.
[This document](https://documents.worldbank.org/en/publication/documents-reports/documentdetail/591411553104368000/march-2019-povcalnet-update-whats-new) outlines the changes made to the underlying data.

# 2019/02/07

National accounts data for Venezuela has been updated to correspond fully to WDI series.

# 2018/09/19

-   The September 2018 global poverty update from the World Bank presents new poverty estimates for 2015, and revises the previously published global and regional estimates from 1981 to 2013.
    The update includes new surveys that have been received and processed, as well as several changes to the existing data.
    Some changes reflect improvements in the welfare aggregate based on new harmonization efforts and more available information.
    [This document](https://documents.worldbank.org/en/publication/documents-reports/documentdetail/800661537207486157/september-2018-povcalnet-update-what-s-new) outlines the changes made to the underlying data by country, and explains the reasons why the changes have been made.
    The 2018 Poverty and Shared Prosperity report (forthcoming in mid-October) will offer a detailed analysis of the latest trends in global and regional poverty, including the 2015 estimates.

-   In this release, we also published the API for accessing the PovcalNet directly without using the Povcalnet web pages.
    User can refer the [API specification document](http://iresearch.worldbank.org/PovcalNet/docs/PovcalNet%20API.pdf) for the syntax of API.

# 2018/04/18

-   The April 2018 update to PovcalNet involves several changes to the data underlying the global poverty estimates.
    We include new surveys that we have received and processed, as well as several changes to the existing data.
    Some changes reflect improvements in the welfare aggregate based on new harmonization efforts and more available information.
    Other changes involve corrections of minor errors in the construction of the welfare aggregate.
    When relevant, we have also updated some of the auxiliary data, such as the CPIs and national accounts data.
    Finally, we have dropped a few surveys from the database based on data quality concerns.
    [This document](https://documents.worldbank.org/en/publication/documents-reports/documentdetail/173171524715215230/april-2018-povcalnet-update-what-s-new) details the content of and reasoning behind the changes made.

-   As a result of these updates to the database, we have revised the global and regional estimates from 1981 to 2013, originally released in October 2016 and revised in October 2017.
    The World Bank's next major update of global and regional poverty estimates is scheduled for October 2018, where we plan to release global poverty estimates for the reference year 2015.
    This will coincide with the launch of the next Poverty and Shared Prosperity report.

# 2017/10/10

-   While the October 2017 update includes several methodological changes, as well as an update of the underlying economy-level data, we have not estimated global poverty for a new reference year.
    Instead, we have updated the global and regional poverty estimates for reference year 2013 which were originally released in October 2016.
    From now on, we will report updated global poverty estimates only every two years, coinciding with the publication of the Poverty and Shared Prosperity reports.
    Changes in the global poverty estimates from one year to the next are small, in particular when one considers the likely uncertainties involved in these estimates.
    Furthermore, many developing economies, especially those with high concentrations of extreme poverty, lack surveys with an annual frequency.
    Hence, changes from one year to the next for these economies are based on our extrapolation and interpolation methods, which may give rise to additional estimation errors.
    We plan to release global poverty estimates for reference year 2015 in October 2018.

-   We now report a regional poverty estimate for the Middle East and North Africa region in reference year 2013.
    The surveys that we can now include in our database account for more than 40 percent of the regional population, which is the cut-off for reporting a regional poverty estimate.
    This improvement in the population coverage reflects newly available data, as well as the resolution of remaining issues with the 2011 PPPs in the region (see below).

-   In our global count, we no longer assume that the "other high income economies" have no people living in extreme poverty (see the note from 2016/10/01 below for a list of economies that are included in this group).
    We had previously made this simplifying assumption of zero extreme poverty in these economies for the global aggregate (for a discussion [see Ferreira et al., 2016, p. 160](https://link.springer.com/content/pdf/10.1007%2Fs10888-016-9326-6.pdf)).
    However, as Prof. Anthony Atkinson has pointed out in his report of the Commission on Global Poverty, this assumption is inconsistent with a truly global approach to poverty measurement ([World Bank, 2017, p. 47](https://openknowledge.worldbank.org/bitstream/handle/10986/25141/9781464809613.pdf)).
    He advised that we should bring these economies into our scope of analysis.
    This is even more important, as we now report global and regional poverty at additional higher lines (next bullet).

-   We now report global and regional poverty estimates for two additional poverty lines, \$3.20/day and \$5.50/day (both in 2011 PPPs).
    Poverty estimates for these lines are reported in addition to the \$1.90 International Poverty Line, which remains our headline poverty threshold, and continues to define the World Bank's goal of ending global poverty by 2030.
    The \$3.20 and \$5.50 lines are based on the national poverty lines typically found in lower- and upper-middle income economies, respectively.
    The methodology for deriving these new poverty lines is given in [Jolliffe and Prydz (2016)](https://link.springer.com/article/10.1007/s10888-016-9327-5?noAccess=true).
    Of course, PovcalNet continues to allow users full flexibility in choosing their own poverty line.

-   For Egypt, Iraq, Jordan, Lao PDR, Myanmar and Yemen we use regression-based 2011 PPP exchange rates estimated from a revised model.
    We were concerned about the reliability of the official PPP exchange rates in these economies, for example due to poor coverage or quality of the underlying price collection, or large discrepancies between CPI- and PPP-based inflation rates (see Ferreira et al., 2016).
    Atamanov et al. (2017) [available by emailing the PovcalNet team] describe the model used to predict PPP exchange rates for these economies.
    In the previous update (October 2016), PovcalNet used the following PPPs for these economies: For Lao PDR, we used the official 2011 PPP.
    Egypt, Iraq, Jordan and Yemen used an older regression-based PPP, which our new PPPs improve upon.
    For Myanmar, we had no household survey data available.

-   We have removed poverty estimates for Cambodia until further analytical work is carried out.
    Close examination of the household survey and price data suggested problems with the household survey-based welfare aggregate, producing implausibly low poverty rates.
    According to these estimates, Cambodia's poverty rate was much lower than what is expected from its GDP per capita.
    Furthermore some non-income welfare indicators are much lower in Cambodia than in economies with comparable extreme poverty rates.
    We have removed the Cambodia data pending further analytical work to improve the reliability of the household survey-based consumption aggregate.
    Therefore, like any other economy without survey data, Cambodia now enters the regional and global aggregate with the regional (East Asia and Pacific) headcount ratio.

-   PovcalNet data for several economies in East Asia and the Pacific have been updated to incorporate a spatial adjustment of the welfare aggregate.
    Adjusting for cost-of-living differences across regions within an economy arguably results in a more accurate representation of well-being.
    Furthermore, this practice is in line with the spatial adjustments in other regions, such as Latin America, as detailed [here](https://link.springer.com/article/10.1007/s10888-016-9326-6).
    Economies that were updated with a spatially-deflated welfare aggregate include: Kiribati, Lao PDR, Papua New Guinea, Philippines, Timor-Leste, Tonga, Tuvalu, Vietnam, Vanuatu, and Samoa.

-   The data for the "other high income" economies, as well as some of the income surveys in Europe and Central Asia, have a small number of observations with negative incomes, which we have dropped from the underlying database.
    These observations are typically the result of negative profits for self-employed individuals.
    The observed negative income is unlikely to reflect the permanent income of the household.
    It also does not reflect household consumption for this year, since households smooth their consumption from one year to the next, and consumption expenditure by definition cannot be negative.
    In other words, for those negative income households, we do not observe a level of income or consumption expenditure that would be a good predictor of their welfare in this year, so we exclude them from the analysis.
    This is consistent with our approach adopted for economies in Latin America and the Caribbean ([see SEDLAC methodological documents, p. 20](https://www.cedlas.econo.unlp.edu.ar/wp/estadisticas/sedlac/)).
    We view this as a temporary fix until we can develop a better method to impute a more meaningful level of income or consumption for these observations.

-   Around 119 new household surveys have been added to the World Bank's global database, bringing the total count of household surveys to 1548.
    Many surveys have also been updated, reflecting corrections and improvements to the data sources.
    In particular, all the estimates drawn from the [Luxembourg Income Study](https://www.lisdatacenter.org/) (used for some of the "other high income economies") have been updated.
    For Haiti in 2012, we now use consumption expenditure instead of income as the welfare measure, which dramatically reduces the estimated poverty headcount ratio.

-   The CPI data are primarily taken from the World Development Indicators.
    [Ferreira et al. (2016)](https://link.springer.com/content/pdf/10.1007%2Fs10888-016-9326-6.pdf)list the economies where alternative CPIs are used.
    As of October 2017, alternative CPIs (monthly CPIs) are also used for Iran and Myanmar.

# 2016/10/01

## Changes in purchasing power parities

In the 2016 PovcalNet update, the poverty measures for all economies are based on consumption PPPs from the 2011 round of data collection by the [International Comparison Program](https://www.worldbank.org/en/programs/icp).
These PPP exchange rates include benchmark economies where actual price surveys were conducted, as well as regression-based PPP estimates where such surveys were not conducted.
Details on the regression model for the PPP estimation can be found in [World Bank (2015)](https://thedocs.worldbank.org/en/doc/711001503680105564-0050022017/original/ICP2011GlobalReport.pdf).
In the 2015 update, a number of economies had still used the 2005 instead of 2011 PPPs.
The following changes have now been made:

1.  For Bangladesh, Cabo Verde, Cambodia, and Lao PDR, the 2005 PPPs are replaced in this round by 2011 PPPs;
2.  For economies in the International Comparison Program region of West Asia, 2011 regression-based consumption PPPs are used in this round.

## Changes in household survey data

More than 35 new household surveys have been added to the World Bank's global database, and over 100 other surveys have been updated.
About 1240 household surveys are used in this round.

## Changes in the CPI, population data, and national accounts data

-   The CPI data used by PovcalNet are given here.
    For 116 economies, the CPI data used for global poverty measurement are taken from the [World Development Indicators](https://datatopics.worldbank.org/world-development-indicators/).
    For some economies we used alternative CPIs: China and India use rural and urban CPIs (as provided by the national statistics offices).
    Monthly CPIs are used by 25 economies; most are in Latin America and the Caribbean.
    Another seven economies: Bangladesh, Cambodia, Ghana, Iraq, Lao PDR, Malawi, and Tajikistan, use the implied, that is, the expected CPI.

-   Population data have also been updated, with changes for most economies.
    In 21 economies, the changes have been particularly significant, ranging from 0.5 million to 4.5 million.

-   National accounts data have also been updated.
    Per capita GDP, private consumption, and expenditure data have all been updated.

## Middle East and North Africa Region

-   As part of the 2016 update, a detailed reassessment of the 2011 PPPs has been conducted for Egypt, Iraq, Jordan, and the Republic of Yemen.
    It found that the coverage and quality of the 2011 PPP price data for most of these economies were hindered by the exceptional period of instability they faced at the time of the 2011 exercise of the International Comparison Program.
    Moreover, using alternative regression-based PPPs also seems to underestimate poverty substantially in these economies, as well as in Lebanon and the Syrian Arab Republic (but not in West Bank and Gaza).

-   The exclusion of economies with problematic 2011 PPPs (Egypt, Iraq, Jordan, and the Republic of Yemen), as well as the lack of recent data on Algeria and Syria, imply that the remaining economies account for only a third of the region's population.
    This is less than the 40 percent threshold of regional population coverage that we impose for reporting regional poverty estimates.
    Furthermore, the lack of new data in several economies that have recently been affected by instability and civil conflicts, could lead to a serious underestimation of regional poverty rates.

-   As a compromise between precision and coverage, regional poverty totals and headcount ratios are not reported for the Middle East and North Africa, but an estimate of the number of the poor for the region is included in the global total (based on regression-based PPPs and 2011 PPPs, depending on the economy).

## China's 2013 survey

-   In the 2013 data, a large part of the decline in poverty in East Asia and the Pacific is attributable to China and Indonesia.
    The 2013 household survey in China is the first integrated nationwide household survey in the economy.
    This means that it is not comparable to previous household surveys, in which rural and urban areas were sampled separately.
    In addition, the most significant change in the 2013 survey relative to previous surveys was the inclusion of imputed rents in income and consumption aggregates.

-   Between 2012 and 2013, China's poverty rate at the \$1.90 poverty line declined by about 4 percentage points, of which half, that is, about 2 percentage points, can be traced to changes in the survey methodology.
    In other words, the actual poverty reduction not explained by methodological changes was 2 percentage points between 2012 and 2013 ([see World Bank, 2016, Table 2B.1, p. 49](https://openknowledge.worldbank.org/bitstream/handle/10986/25078/9781464809583.pdf)).

-   Furthermore, the World Bank's poverty estimates on China are based on grouped distributions, which are often not as precise as direct estimates based on the full distribution of household income and consumption aggregates.
    In 2013, China's poverty headcount ratio under the \$1.90 poverty line was 2.2 percent using individual record data, as confirmed by the National Bureau of Statistics, while it was 1.9 percent based on grouped data.

## Definition of geographical regions and industrialized economies

In the past, PovcalNet used the World Bank's income classification back to 1990 to track the Millennium Development Goals.
Starting this round, a new regional geographical classification is used.
Two groups of economies are included in the six geographical regions presented in PovcalNet: (a) [low- and middle-income economies](https://datahelpdesk.worldbank.org/knowledgebase/articles/906519-world-bank-country-and-lending-groups), and (b) economies eligible to receive loans from the World Bank (such as Chile) and recently graduated economies (such as Estonia).

The remaining economies have a high-income status and are reported as the group of "Other high income" in PovcalNet.
This group includes the following economies: Andorra; Antigua and Barbuda; Aruba; Australia; Austria; The Bahamas; Bahrain; Barbados; Belgium; Bermuda; British Virgin Islands; Brunei Darussalam; Canada; Cayman Islands; Channel Islands; Curacao; Cyprus; Denmark; Finland; France; French Guiana; French Polynesia; Germany; Gibraltar; Greece; Greenland; Guadeloupe; Guam; Iceland; Ireland; Isle of Man; Israel; Italy; Japan; Korea; Kuwait; Liechtenstein; Luxembourg; Macao SAR, China; Malta; Monaco; Netherlands; New Caledonia; New Zealand; Norway; Oman; Portugal; Qatar; Saint-Martin; Saudi Arabia; Singapore; Sint Maarten; Spain; St. Kitts and Nevis; Sweden; Switzerland; Taiwan, China; Turks and Caicos Islands; United Arab Emirates; United Kingdom; United States; and the U.S.
Virgin Islands.
All economies not on this list, but included in the World Development Indicators, are included in their respective geographical region.

## Changes in user interface

A new analytical function is provided for users to analyze their own distribution.
This replaces the legacy Povcal.exe provided in the earlier version.
The data submitted to PovcalNet will not be stored by the PovcalNet site, nor will PovcalNet do any currency conversion in the calculation.
Therefore, users should use the same currency unit in the poverty line as in the distributional data.

# 2015/10/07

-   The October 2015 update of global poverty estimates covers the period from 1981 to 2012 and is based on 2011 PPP.
    A parallel site, [PovcalNetPPP2005](http://iresearch.worldbank.org/PovcalNetPPP2005/), continues to report data using 2005 PPP.
    However, the underlying data used by the 2005 PPP site have not been updated.

-   The global poverty line is changed from \$1.25/day in 2005PPP to \$1.90/day in 2011PPP.
    The methodology used to derive the new line is described in [Ferreira et al. (2016)](https://link.springer.com/content/pdf/10.1007%2Fs10888-016-9326-6.pdf).

-   Substantial update of the underlying distributional files.
    A total of 1205 datasets are used in this round.

-   CPI, population and national accounts data are all updated.

-   The 2005 PPP is still used for the following economies: Bangladesh, Cabo Verde, Cambodia, Lao and Jordan.
    These economies are included in the regional and global aggregate (at \$1.90 in 2011 PPP) with their national headcount ratio estimated from \$1.25 in 2005 PPP.

-   China has a new integrated (rural and urban areas are no longer sampled separately) household survey starting in 2013.
    This new survey is not used in the October 2015 update.
    For a more detailed explanation, please see the [2016 Poverty and Shared Prosperity Report.](https://openknowledge.worldbank.org/bitstream/handle/10986/25078/9781464809583.pdf?sequence=24&isAllowed=y)

-   Country-level poverty estimates based on 2011 PPPs for Algeria, Egypt, Iraq, Syria and Yemen are not available in this round because of inexplicably large deviations between CPI and PPP inflations, outdated surveys or major ongoing revisions to surveys, and ongoing conflicts.
    While no economy-level poverty estimates are reported for these economies, poverty estimates for these economies are calculated for inclusion in the global aggregate.

# 2014/12/05 - PovcalNet Widget goes for testing.

The PovcalNet widget is a plugable element for doing poverty analysis in any web pages.
It can be embedded into a third-party site and used by any user.
The underline methodology and data are the same as the full scale PovcalNet.
In addition, the PovcalNet widget is implemented in multiple languages.
It can also be configured with a default economy and default poverty line.
Please see the [widget page](http://iresearch.worldbank.org/PovcalNet/widget.htm) for full technical details.

# 2014/10/09

The entire set of household surveys for the Europe and Central Asia region has been updated by the ECA data team.
This includes more than 246 surveys from almost all the 29 economies.
For details of those survey data, see ECAPOV, a database of standardized household surveys in the Europe and Central Asia maintained by the World Bank.

The entire set of household surveys for the Latin American and the Caribbean region has been updated.
This includes more than 280 surveys from almost all the 25 economies.
For details, see [SEDLAC](https://www.cedlas.econo.unlp.edu.ar/wp/en/estadisticas/sedlac/).

Many new surveys have been added into PovcalNet from several economies in East Asia, Sub-Saharan Africa and South Asia, spanning the period between 2010 and 2012/13.

Surveys for high-income economies have been included in this update.
User can calculate shared prosperity for those economies.
However, the estimation of the global poverty headcount assumes that nobody lives below \$1.25 a day in these economies.
There are some observations with household incomes below \$1.25 per person in these economies, but estimated per capita consumption is above this threshold for nearly everyone.
Due to some negative incomes reported in the data, some of these economies have very large poverty gap and squared poverty gap indices.

The mean per capita income or consumption for the bottom 10%, 20%, ..., 90% of the population is provided after the decile share table.

# 2014/09/09

-   The household survey data for Brazil has been updated.
    The PNAD data used in PovcalNet for Brazil reflects changes in the weighting of the survey implemented by the Brazilian statistical office (IBGE) in 2013 to the yearly PNAD survey from 2001 to 2012 (nota_tecnica.pdf).
    In addition, the data reflects the use of the Domicilio as the household unit for Brazil, per agreement with the Brazilian authorities.

-   A new algorithm is applied to calculate the income or consumption decile.
    This addresses problems associated with income concentration.

-   The computational problem in estimating the Watts index has been fixed in this round.
